services:
  backend:
    build: ./backend-java
    container_name: jf-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend-angular
    container_name: jf-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
